apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deploy
spec:
  selector:
    matchLabels:
      app: myjavaapp
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
      - name: myjavaapp-container
        image: rohitsharma93/myjavaimage1122:1
        ports:
        - containerPort: 8080
